final_time = 94608000000
mesh_file = "bp1_sym.msh"

[seas]
type = "poisson"
lib = "bp1_sym.lua"
boundary = "boundary"
mu = "mu"
ref_normal = [-1, 0]

[friction]
lib = "bp1_sym.lua"
a = "a"
eta = "eta"
sn_pre = "sn_pre"
tau_pre = "tau_pre"
Vinit = "Vinit"
    [friction.constant]
    b = 0.015
    V0 = 1.0e-6
    L = 0.008
    f0 = 0.6

[fault_output]
prefix = "bp1_sym-fault"
t_max = 9460800
