resolution = 0.125

[elasticity]
lib = "cosine_oscillatory.lua"
force = "force"
boundary = "solution"
solution = "solution"
warp = "warp"
mu = "mu"
lam = "lam"

[generate_mesh]
intercepts = [
    [0, 1],
    [0, 1]
]
bcs = [
    [{bc = "d", plane = 0}, {bc = "d", plane = 1}],
    [{bc = "d", plane = 0}, {bc = "d", plane = 1}]
]

