final_time = 37843200000
mesh_file = "ridgecrest_hf50.msh"
mode = "QDGreen"
type = "poisson"
lib = "matfric_Fourier_main_v6_ab2_Dc1.lua"
scenario = "bp1_sym"
ref_normal = [-1, 0]
boundary_linear = true

[fault_probe_output]
prefix = "receiver_"
t_max = 9460800
probes = [
    { name = "dp000", x = [0.0, 0.0] },
    { name = "dp002", x = [0.0, -0.2] },
    { name = "dp004", x = [0.0, -0.4] },
    { name = "dp006", x = [0.0, -0.6] },
    { name = "dp008", x = [0.0, -0.8] },
    { name = "dp010", x = [0.0, -1.0] },
    { name = "dp012", x = [0.0, -1.2] },
    { name = "dp014", x = [0.0, -1.4] },
    { name = "dp016", x = [0.0, -1.6] },
    { name = "dp018", x = [0.0, -1.8] },
    { name = "dp020", x = [0.0, -2.0] },
    { name = "dp022", x = [0.0, -2.2] },
    { name = "dp024", x = [0.0, -2.4] },
    { name = "dp026", x = [0.0, -2.6] },
    { name = "dp028", x = [0.0, -2.8] },
    { name = "dp030", x = [0.0, -3.0] },
    { name = "dp032", x = [0.0, -3.2] },
    { name = "dp034", x = [0.0, -3.4] },
    { name = "dp036", x = [0.0, -3.6] },
    { name = "dp038", x = [0.0, -3.8] },
    { name = "dp040", x = [0.0, -4.0] },
    { name = "dp042", x = [0.0, -4.2] },
    { name = "dp044", x = [0.0, -4.4] },
    { name = "dp046", x = [0.0, -4.6] },
    { name = "dp048", x = [0.0, -4.8] },
    { name = "dp050", x = [0.0, -5.0] },
    { name = "dp052", x = [0.0, -5.2] },
    { name = "dp054", x = [0.0, -5.4] },
    { name = "dp056", x = [0.0, -5.6] },
    { name = "dp058", x = [0.0, -5.8] },
    { name = "dp060", x = [0.0, -6.0] },
    { name = "dp062", x = [0.0, -6.2] },
    { name = "dp064", x = [0.0, -6.4] },
    { name = "dp066", x = [0.0, -6.6] },
    { name = "dp068", x = [0.0, -6.8] },
    { name = "dp070", x = [0.0, -7.0] },
    { name = "dp072", x = [0.0, -7.2] },
    { name = "dp074", x = [0.0, -7.4] },
    { name = "dp076", x = [0.0, -7.6] },
    { name = "dp078", x = [0.0, -7.8] },
    { name = "dp080", x = [0.0, -8.0] },
    { name = "dp082", x = [0.0, -8.2] },
    { name = "dp084", x = [0.0, -8.4] },
    { name = "dp086", x = [0.0, -8.6] },
    { name = "dp088", x = [0.0, -8.8] },
    { name = "dp090", x = [0.0, -9.0] },
    { name = "dp092", x = [0.0, -9.2] },
    { name = "dp094", x = [0.0, -9.4] },
    { name = "dp096", x = [0.0, -9.6] },
    { name = "dp098", x = [0.0, -9.8] },
    { name = "dp100", x = [0.0, -10.0] },
    { name = "dp102", x = [0.0, -10.2] },
    { name = "dp104", x = [0.0, -10.4] },
    { name = "dp106", x = [0.0, -10.6] },
    { name = "dp108", x = [0.0, -10.8] },
    { name = "dp110", x = [0.0, -11.0] },
    { name = "dp112", x = [0.0, -11.2] },
    { name = "dp114", x = [0.0, -11.4] },
    { name = "dp116", x = [0.0, -11.6] },
    { name = "dp118", x = [0.0, -11.8] },
    { name = "dp120", x = [0.0, -12.0] },
    { name = "dp122", x = [0.0, -12.2] },
    { name = "dp124", x = [0.0, -12.4] },
    { name = "dp126", x = [0.0, -12.6] },
    { name = "dp128", x = [0.0, -12.8] },
    { name = "dp130", x = [0.0, -13.0] },
    { name = "dp132", x = [0.0, -13.2] },
    { name = "dp134", x = [0.0, -13.4] },
    { name = "dp136", x = [0.0, -13.6] },
    { name = "dp138", x = [0.0, -13.8] },
    { name = "dp140", x = [0.0, -14.0] },
    { name = "dp142", x = [0.0, -14.2] },
    { name = "dp144", x = [0.0, -14.4] },
    { name = "dp146", x = [0.0, -14.6] },
    { name = "dp148", x = [0.0, -14.8] },
    { name = "dp150", x = [0.0, -15.0] },
    { name = "dp152", x = [0.0, -15.2] },
    { name = "dp167", x = [0.0, -16.7] },
    { name = "dp182", x = [0.0, -18.2] },
    { name = "dp197", x = [0.0, -19.7] },
    { name = "dp212", x = [0.0, -21.2] },
    { name = "dp227", x = [0.0, -22.7] },
    { name = "dp240", x = [0.0, -24.0] }
]
